### ISSUE TITLE
[BUG] Incorrect link in Korean Docs 

### ISSUE THREAD

**Issue by miguelmiguelasd** [near/docs#1388] opened 2023-04-18 07:30 UTC
It seems like en page is open when we click each icon in the Korean docs. Could you kindly look into it?

https://docs.near.org/ko/

Thank you

**Comment by miguelmiguelasd** [comment] 2023-04-18 07:34
Below is the example:
https://github.com/near/docs/blob/9d1d6efa4fef9b39b45e3c4a3858e41e45c96d39/docs/index.md?plain=1#L48

**Comment by miguelmiguelasd** [comment] 2023-04-18 07:37
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/122418296/232705572-7f05c207-76d2-450a-b4dc-eb04e307ce40.png">

When I click each icon, english version of docs is deployed...

**Comment by think-in-universe** [comment] 2023-04-18 07:41
The cause of the issue is the MDX components that we have created didn't take into account i18n paths (`/ko`, `/vi`, `/zh-CN`, etc.) in its implementation. This could be fixed by updating the MDX components I think.

**Comment by bucanero** [comment] 2023-04-24 21:30
@think-in-universe I have made a fix on `featurelist.js`, please review the PR when you have a chance.

**Closed** 2023-04-25 12:13 UTC
Labels: bug
